services:
  db:
    image: mongo:7
    container_name: inventario-db
    environment:
      MONGO_INITDB_DATABASE: sistema_inventario
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - inventario-network

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: inventario-backend
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_DB}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      APP_SEED_ADMIN: ${APP_SEED_ADMIN}
      APP_SEED_ADMIN_EMAIL: ${APP_SEED_ADMIN_EMAIL}
      APP_SEED_ADMIN_PASSWORD: ${APP_SEED_ADMIN_PASSWORD}
      APP_SEED_ADMIN_NOMBRE: ${APP_SEED_ADMIN_NOMBRE}
      APP_CORS_ORIGIN: http://localhost:8081,http://frontend:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - inventario-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: inventario-frontend
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - inventario-network

networks:
  inventario-network:
    driver: bridge

volumes:
  mongo_data:
